#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib" }

# Start command line interface for application
require Mojolicious::Commands;

use Plack::Builder;

builder {
    enable 'Plack::Middleware::ReverseProxy';
    Mojolicious::Commands->start_app('EBank');
};
